### ISSUE TITLE
fieldtrip/FMAT/eeglab duplicates

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#10]
functions to check: (delete once a pair has been checked/merged, close issue when all are crossed off)

./externalPackages/fieldtrip-20150209/external/eeglab/sobi.m
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/sobi.m

./externalPackages/fieldtrip-20150209/external/eeglab/jader.m
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/jader.m

./externalPackages/fieldtrip-20150209/external/eeglab/binica.m
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/binica.m

./externalPackages/fieldtrip-20150209/external/eeglab/COPYING
./externalPackages/eeglab14_0_0b/eeglablicense.txt

./externalPackages/fieldtrip-20150209/external/eeglab/floatwrite.m
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/floatwrite.m

./externalPackages/fieldtrip-20150209/external/eeglab/varimax.m
./externalPackages/eeglab14_0_0b/functions/miscfunc/varimax.m

./externalPackages/fieldtrip-20150209/external/eeglab/binica.sc
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/binica.sc

./externalPackages/fieldtrip-20150209/external/eeglab/ica_linux
./externalPackages/eeglab14_0_0b/functions/resources/ica_linux

./externalPackages/fieldtrip-20150209/external/eeglab/floatread.m
./externalPackages/eeglab14_0_0b/functions/sigprocfunc/floatread.m

./externalPackages/fieldtrip-20150209/external/eeglab/pcsquash.m
./externalPackages/eeglab14_0_0b/functions/miscfunc/pcsquash.m

/externalPackages/fieldtrip-20150209/external/neuroscope/private/isradians.m
./externalPackages/FMAToolbox/Helpers/isradians.m

./externalPackages/fieldtrip-20150209/external/neuroscope/private/wrap.m
./externalPackages/FMAToolbox/Helpers/wrap.m

./externalPackages/fieldtrip-20150209/external/neuroscope/LoadSpikeAmplitudes.m
./externalPackages/FMAToolbox/IO/LoadSpikeAmplitudes.m

./externalPackages/eeglab14_0_0b/sample_locs/GSN-HydroCel-32.sfp
./externalPackages/fieldtrip-20150209/template/electrode/GSN-HydroCel-32.sfp

/externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_1222.vol
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_1222.vol

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_14038-1.bps
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_14038-1.bps

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_5054-1.bps
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_5054-1.bps

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_1222-1.bnd
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_1222-1.bnd

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_5054-1.bpl
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_5054-1.bpl

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_1222-1.bps
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_1222-1.bps

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_14038.vol
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_14038.vol

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_14038-1.bnd
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_14038-1.bnd

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_5054-1.bnd
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_5054-1.bnd

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_14038-1.bpl
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_14038-1.bpl

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_1222-1.bpl
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_1222-1.bpl

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/skin/standard_skin_5054.vol
./externalPackages/fieldtrip-20150209/template/headmodel/skin/standard_skin_5054.vol

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_alphabetic.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_alphabetic.elc

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_prefixed.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_prefixed.elc

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_primed.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_primed.elc

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_1020.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_1020.elc

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_postfixed.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_postfixed.elc

./externalPackages/eeglab14_0_0b/plugins/dipfit2.3/standard_BEM/elec/standard_1005.elc
./externalPackages/fieldtrip-20150209/template/electrode/standard_1005.elc

**Comment by brendonw1** [comment]
That's nice

**Comment by DavidTingley** [comment]
fieldtrip moved to external repository (https://github.com/buzsakilab/fieldtrip)
