### ISSUE TITLE
SetCurrentSession not backwards compatable

### ISSUE THREAD

**Issue by samamckenzie** [buzsakilab/buzcode#107]
SetCurrentSession is the heart of FMA and the current buzcode version is named the same but breaks backwards compatibility. I recommend renaming the buzcode version or fixing the backwards compatibility.

**Comment by dlevenstein** [comment]
I don't think we've made any changes to SetCurrentSession, we don't use it at all with any buzcode functions/workflow. Do you know where the break is? 

(i.e. there's not really a buzcode "version" of SetCurrentSession that's different from the FMA version to my knowledge, but it's possible it calls functions that have been changed)

**Comment by brendonw1** [comment]
Didn't David change setcurrentsession a long while back?

**Comment by DavidTingley** [comment]
1) we should be moving away from this approach (so we likely won't be creating a bz_setcurrentsession)
but 2) the version here is compatible all versions of SetCurrentSession that I have seen within the lab (~5).  Could you be more specific about the error you are seeing?

**Comment by samamckenzie** [comment]
I can pass just the filename of the XML, no flag.

But I seem to be unique here, so let's close this issue and I will drop
setcurrentsession for lab code
