### ISSUE TITLE
bz_LFPfromDat update

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#112]
currently bz_LFPfromDat just downsamples.  Should also low pass filter like NDManager...

**Comment by brendonw1** [comment]
bz_LFPfromDat.m
- Determine I/O's of interest for this function.  Proposals:
    - Output freq
    - filter highpass cutoff
    - ?other
- Comment/document properly.
- I'd eliminate the following redundant functions...
      - bz_GetLFP.m
      - bz_LFPFromDat.m (Preprocessing folder)
      - bz_LFPFromAbf.m (Preprocessing folder)
      - ?others    
- Still need to understand filter-setting using "ratio" variable @samamckenzie can you help?

**Comment by dlevenstein** [comment]
Re: redundant functions
-Definitely we should get rid of the old bz_LFPFromDat. I'll update bz_LFPFromABF to use the same method (some of the data from the Rudy lab (via pclamp) gets the lfp in an abf file, so I need this f'n)
-we still need bz_GetLFP (our primary function for loading the .lfp file into matlab for analysis, this is a different functionality from LFPfromDat).

**Comment by dlevenstein** [comment]
thanks for merging #175 @samamckenzie :D    we can use this issue for our main discussion (as we'll probably have multiple pull requests relating to this issue).  You can reference this Issue page using #112 in your pull requests

**Comment by dlevenstein** [comment]
Reposting from @brendonw1 in #175 (which is closed now):

Given that, should this new bz_LFPFromDat be in preprocessing rather than
io as it is now?   I'd say yes.

Sam how we use range.  Can write it so a specific cutoff frewuency is given
at the top (as a constant or by user) and then the math for division etc is
handled below to handle that?




DL: I agree move the new function to preprocessing

**Comment by brendonw1** [comment]
Yay teamwork

**Comment by brendonw1** [comment]
Git in action

**Comment by dlevenstein** [comment]
Flag: 
One thing we should make sure to do is a direct comparison test:
-run the same file with NDManager and with bz_LFPfromDat and make sure they end up giving the same output

**Comment by samamckenzie** [comment]
+1 DanL

I am working on the lopass user def now

**Comment by dlevenstein** [comment]
It seems like there are two outstanding to-dos with this issue, and then we can merge dev to master with the new function:
1) delete unnecessary files from the surrey toolbox
2) test old vs new processing to make sure they are the same

Is there anything else? (No rush, just documenting it here so we don't forget where were at.)

**Comment by brendonw1** [comment]
Right this seems correct to me.
Re #1 - we can run depfun
- or if we think it’s a good toolbox to generally have we could keep the
whole thing

Re #1
How will we determine “good enough”?

**Comment by dlevenstein** [comment]
Hm - one almost too stupid way would be to calculate the correlation between the two signals?  Visual inspection (especially around spike times) is another good idea. Could use a coherogram to see if there is any frequency-specific differences. Any other suggestions?

What is depfun?

**Comment by brendonw1** [comment]
Depfun is a matlab function to give dependencies

Yeah as for the spectral thing - I’m sure the old and new filters will
differ. But I’m not sure how to say what’s too different and what’s not.
Spike times sure. Maybe also spectrum of various important lfp states like
ripples, theta, cortical nrem. Make sure for hpc and cx the nrem and wake
states remain differentiable.
And other that just keep eyes open for obvious problems?

**Comment by dlevenstein** [comment]
hey all..... this somehow got pulled into master. we're not sure how, but it's as good a time as any to wrap it up.

1) there's an open pull request #176 that should be merged in, 
2) we need to delete the files from surrey
3) we need to test the function

anything else?

david and I will try to knock these things off tomorrow so they don't stick around in master.

**Comment by dlevenstein** [comment]
Here's the comparison between raw (dat), unfiltered, and filtered .lfp file. I'm going to run a comparison next with one of david's files (using the NDManager pipeline) so we can see how comparable they are.

![screenshot - 05092018 - 04 38 00 pm](https://user-images.githubusercontent.com/7265688/39839479-41235b12-53aa-11e8-9774-b9f2a1e5c6f8.png)

**Comment by brendonw1** [comment]
Is it pretty quick?
It’s definitely somewhat better than unfiltered.

Thanks Dan

**Comment by dlevenstein** [comment]
it was a little while with the longer recording (took about 20 minutes?, certainly not unmanageable). but I don't have a GPU, so it'll go even faster with the gpu

**Comment by brendonw1** [comment]
Ah cool

**Comment by dlevenstein** [comment]
this issue was solved by some PR a while ago...
