### ISSUE TITLE
Rewrite without bash/C dependencies

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#123]
MakeClassicFet.m

**Comment by brendonw1** [comment]
I think this is done by Peter now right? @petersenpeter

**Comment by samamckenzie** [comment]
I am working on this now building off of Peter's. does this live in your personal code repo or do we migrate the kilosort wrapper over to buzcode?

**Comment by brendonw1** [comment]
I think the consensus was to not merge kilosortwrapper w buzcode.

**Comment by brendonw1** [comment]
Do you have the code?

**Comment by samamckenzie** [comment]
yah, I am testing it now
