### ISSUE TITLE
WaveSpec dependency

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#127]
@dlevenstein, could we move wavespec.m into buzcode? there are a few functions that call it

**Comment by dlevenstein** [comment]
Yes. Shall we rename it bz_WaveSpec and make some updates for buzcode integration. (I.e. input/output in the proper structure format?, like bz_Filter)

**Comment by raswanson** [comment]
Agreed - before we add to buzcode we should also confirm we're doing wavelet normalization correctly. Ideally the output of the convolution of our signal with a given wavelet is in mV (not the classic 'au'). Can help out with this.

**Comment by brendonw1** [comment]
Is this a wavelet toolbox?  We already have awt_freqlist in there as a
basic wavelet generation/convolution function.  Don't know if it's
redundant to have two?  Unless this is soemthing else

**Comment by raswanson** [comment]
No - this is a set of fxs Dan and I wrote based on the wavelets chapter of the textbook 'Analyzing Neural Time Series Data ' (i. fx to convolve in frequency domain, ii. fx to make a wavelet, iii. wrapper fx WaveSpec to convolve signal with a family of wavelets) .  Will check out awt_freqlist to make sure it isn't redundant. If it is and we decide to use it, we will need to change some dependencies that a few other fxs have.

**Comment by brendonw1** [comment]
It does sound redundant, but if it's home-brewed then that's something in
and of itself!

**Comment by DavidTingley** [comment]
bz_wavespec is now in 'circ-dev' branch, will get into 'master' with the next pull request.

If someone wants to work in the normalization stuff, great, though I am skeptical as voltage amplitudes aren't stored with LFP or sessionInfo data for most lab data (so we'd be guessing..)
