### ISSUE TITLE
bz_GetSpikes requires .spk channels even when 'getWaveforms'==false

### ISSUE THREAD

**Issue by bendichter** [buzsakilab/buzcode#132]
```matlab
bz_GetSpikes(...,'getWaveforms',false)
```
shouldn't require .spk files to be in the directory. If you run it on such a basePath, it will search for .spk files (which are unused) and throw an error because it fails to find them.

**Comment by brendonw1** [comment]
David, what do you think?  I think this seems reasonable.

**Comment by dlevenstein** [comment]
I agree. This is an issue.  Thanks for addressing it in #131 :D   
I'll get a chance to look over the code and pull it in tomorrow.

**Comment by bendichter** [comment]
Great, thanks for taking a look at this, Brendon and David :-) I'm just bringing up little glitches I come up against as I try to use the code. I don't want to overstep and violate any lab standards or conventions. I'm happy to work with you guys in code review.
