### ISSUE TITLE
octave compatibility: inputParser validation functions

### ISSUE THREAD

**Issue by bendichter** [buzsakilab/buzcode#136]
https://github.com/buzsakilab/buzcode/blob/4e165efea141b94848dac427a2754bb5a19b5180/io/bz_GetLFP.m#L62

Unfortunately, this line exposes [an octave bug](http://savannah.gnu.org/bugs/?49793): MATLAB's `inputParser` accepts validation functions that output nothing (e.g. `assert`), however Octave requires validation functions to output `true` or `false`. Fixing this isn't hard. The simplest way to do it would be:
```matlab
channelsValidation = @(x) isnumeric(x) || strcmp(x,'all');
```
but it removes that nice error message. I personally think the code and comments are clear without it, but it's a judgement call

P.S. I know it's a bit presumptuous of me to  invite myself to this repo and assume that you all care about octave compatibility. I'd like to run this code on nodes of a supercomputer, and this is the easiest way for me to do it. I want to develop as a team and keep you all in the loop about these changes, but then again if you all have no particular interest in octave I can fork this repo and keep octave-related issues to myself :-)

**Comment by dlevenstein** [comment]
You're good - feel free to make the fix!  Happy to have the help with development

**Comment by bendichter** [comment]
actually this opened a flood of compatibility issues in the signal processing toolbox when butter is called, so maybe this isn't the way to go..

**Comment by DavidTingley** [comment]
I am all for breaking away from MATLAB dependence.  We've talked about switching to python but octave may be a better way to preserve matlab functionality for members who aren't looking to dive into programming. 

Please keep these issues coming 👍 

maybe we could set up an 'octave' branch to try these things out?

**Comment by bendichter** [comment]
@DavidTingley I think that's a good idea. It will take a bit of shifting around but I think there's a possibility of an octave compatible version without too *too* much change. I think `fir1` works fine in octave for instance, so we can swap that in for `butter` in this case.

Also, I'm building a repo in python that works directly NWB files I'm creating from your data and I've ported a few functions from this repo. Feel free to check out my progress as I go and offer suggestions or fork if you'd like: https://github.com/bendichter/ephys_analysis
