### ISSUE TITLE
what is the structure of a "behavior" .mat file?

### ISSUE THREAD

**Issue by bendichter** [buzsakilab/buzcode#142]
I see that several of the analyses require "behavior" .mat files, but I am working with some of Yuta's data that appears to predate this convention. Would you mind adding documentation somewhere that indicates the expected structure of this file?

**Comment by DavidTingley** [comment]
Check this out,

https://github.com/buzsakilab/buzcode/wiki/Data-Formatting-Standards#behavior

and this is an example struct,

https://github.com/buzsakilab/buzcode/blob/master/exampleDataStructs/fbasename.behavior.mat

**Comment by bendichter** [comment]
awesome, thanks!

**Comment by dlevenstein** [comment]
note: feel free to improve the wiki if you find anything to be poorly-documented. Some parts are better-developed than others.
