### ISSUE TITLE
TheStateEditor save/update figures in StateScoreFigures folder

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#147]
Running sleepscoremaster creates easy to browse figures in /StateScoreFigures but these are not updated by TheStateEditor when manual tweaking is done.  It would be nice to keep the figures up to date with what is actually saved in the *.states.mat

**Comment by brendonw1** [comment]
Sorry I have never used those figures... you prefer them over
TheStateEdtior itself?   They seem extraneous to me

**Comment by dlevenstein** [comment]
I use them

**Comment by brendonw1** [comment]
I see.  OK.  I've never much paid attention to that code, but maybe I can
try to encapsulate it in a way that makes it easy to call from
TheStateEditor.  A couple of things 1) Dan is it OK if I wait until you
finish our other edits to that code? 2) when do you want the figures to be
generated?  whenever there's a "save" action?  I can put some time into it
if others use it.

**Comment by dlevenstein** [comment]
I'm going to add this when I finish my changes. It's just a matter of calling makestatescorefigures or whatever they function is called when you save updated states.

**Comment by DavidTingley** [comment]
#90 falls into this as well, two birds one PR...

**Comment by dlevenstein** [comment]
This is addressed by #178
