### ISSUE TITLE
bz_FindRipples is crashing matlab 

### ISSUE THREAD

**Issue by stephielynn921** [buzsakilab/buzcode#152]
Had this problem with 2017a, but I downloaded 2016b and when I run bz_findRipples Matlab crashes and closes. The error is: 

MATLAB is selecting SOFTWARE OPENGL rendering.
*** Error in `/usr/local/MATLAB/R2016b/bin/glnxa64/MATLAB': malloc(): memory corruption (fast): 0x00007f17c45f8370 ***
Segmentation fault (core dumped)

**Comment by DavidTingley** [comment]
@stephielynn921, can we debug which line it is failing on?  This is an OS error or some sort

**Comment by DavidTingley** [comment]
also give this a shot

`matlab -nosoftwareopengl`

**Comment by stephielynn921** [comment]
So when matlab runs line 99, it crashes. 

The whole elseif statement is:
elseif isnumeric(varargin{1}) % if first arg is filtered LFP
    addRequired(p,'lfp',@isnumeric)
    addRequired(p,'timestamps',@isnumeric)
    parse(p,varargin{:})
    signal = bz_FilterLFP(double(p.Results.lfp),'passband',[130 200]);
    timestamps = p.Results.timestamps;
end

but when I run the timestamps line (so the completion of the elseif statement), that is when matlab has a memory corruption/segmentation fault.

**Comment by DavidTingley** [comment]
tracked down to a bug in bz_Filter.m in the current master branch, switching to circ-dev branch fixes this for now

**Comment by DavidTingley** [comment]
'butter' input didn't exist in master branch version of bz_Filter.  This is fixed as soon as circ-dev is pulled into master

**Comment by brendonw1** [comment]
David, thank you for all this
