### ISSUE TITLE
database updating access denied

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#154]
Error using database.jdbc.connection/update (line 347)
Unable to complete update operation. UPDATE command denied to
user 'buzsakid_contrib'@'mcnat126-19.med.nyu.edu' for table
'Datasets'

Hey @petersenpeter, it looks like we need to change the permission on the database side so that we can sync files/folders into the SQL database

**Comment by petersenpeter** [comment]
For now, submit to the secondary database called buzsakid_submitdataset,
instead of buzsakid_metadata. Use the scripts I am submitting now to
buzcode.

2018-03-07 15:51 GMT-05:00 David Tingley <notifications@github.com>:

**Comment by DavidTingley** [comment]
thanks!
