### ISSUE TITLE
FilterX.mexw64 terminats matlab?

### ISSUE THREAD

**Issue by gmbcrazy** [buzsakilab/buzcode#179]
I complied FilterX.c into FilterX.mexw64 successfully. 

But when I run it, matlab always get terminated.

I'm using matlab 2017b.

**Comment by samamckenzie** [comment]
that's an external package from here

https://www.mathworks.com/matlabcentral/fileexchange/32261-filterm

and tis a known issue

Michele Giugliano
<https://www.mathworks.com/matlabcentral/profile/authors/2049928-michele-giugliano>

18 Mar 2018

on R2017a, the test suite crashes MATLAB every time it runs. :-(

**Comment by gmbcrazy** [comment]
Thanks a lot,Sam?

Do you know if the only solution is use old version of matlab? 2008?

**Comment by samamckenzie** [comment]
I don't see any dependencies on that function, where is it used?

sam

**Comment by dlevenstein** [comment]
I think it's called via FilterM in bz_Filter?
We should include a check in any functions that call FilterX for the matlab version, and then call the slower built in filter if the user is running R2017a

**Comment by gmbcrazy** [comment]
It looks work for matlab R2009a
https://www.mathworks.com/matlabcentral/fileexchange/32261-filterm

Lu

**Comment by raswanson** [comment]
@dlevenstein I think that's an important fix - @samamckenzie  we updated bz_Filter to use filtfiltM a while ago and no other fxs in buzcode use it.

**Comment by raswanson** [comment]
This also brings up an important general point. Whenever adding external dependencies to fxs (and adding extra kludge to accommodate those dependencies), we need to weigh the costs/benefits. In this case, filtfiltM is MUCH faster, so I think the matlab version check is worth it.

**Comment by brendonw1** [comment]
I totally agree
We're kind of committing to the idea that this stuff works as well as we
can make it
