### ISSUE TITLE
Probe Geometric and hc-11 eeg

### ISSUE THREAD

**Issue by gmbcrazy** [buzsakilab/buzcode#182]
Hi, I'm trying to get into hc-11 data sets, some of the data were recorded by BZ64-6x10 probe.  I'm quite confused how I could match the eeg data to the Probe Channels.

 file='Achilles_10252013\Achilles_10252013.eeg';
lfp = bz_LoadBinary(file,'frequency',1250,'start',0,'duration',10,'nChannels',134); 

Thus, lfp is a Time*134 matrix. Each row is a channel. How the row in the matrix corresponds to the probe channel (NeuroNexus)?

When I load the .eeg data in neuroscope, for that file, Chan 60-63 (Neuroscope Chan) extra channels in the probe, corresponds to NeuroNexus Channel 36-39 (Should it be Intan Chan in the NRX_Buzsaki64_6X10.xlsx?).  However, in NRX_Buzsaki64_6X10.xlsx, it corresponds to Ch48-51.

**Comment by brendonw1** [comment]
I just wrote the entire email in italics below below and then I remembered
something, I think Andres Grosmark actually rearranges all channels so 1 is
the highest on shank 1 and 2 is the second highest on shank 1 etc.  So it
might already be in order of
1. Shank 1 Superficial site
.
.
.
10. Shank 1 Deepest site
11. Shank 1 Superficial site
.
.
.
20. Shank 1 Deepest site
21. Shank 1 Superficial site
.
.
.
30. Shank 1 Deepest site

I don't know what they did with the extra 4 channels, maybe they made them
another group at the end of each probe??

If that scheme doesn't work then read below





Oh neuronexus... hm... yes those might be right, it depends on which probes
were used.  The files you cite, such as  NRX_Buzsaki64_6X10.xlsx are
relatively new and correspond with intan recording systems.  While I did
not record this data, it may be that that file corresponds with something
like this:

https://docs.google.com/spreadsheets/d/1iTZo6ELsLXoYVg_j8EMgcrLbzFxMcepAb2BME4R4T50/edit?usp=sharing

If that isn't right, you'll have to figure it out based on this information:

This Buzsaki64Sp here should show you the combination of probe
shank/channel layout and also how each channel pins out to the output pins:
https://drive.google.com/file/d/0B0WCzFWl7GCXdVJMajhDc0RsODhjMFBTTkk2dHA4dlNFTmJz/view?usp=sharing

Then pages 25-26 show the preamplifier the probes were plugged into... the
numbers here specify the numbers in the amplifed recording :
https://drive.google.com/file/d/1yIc84Cssu1HExGEfOzx-f52UcupRfeD9X01SoAdC5fd0SLIJyJFhT_I5hlR1/view?usp=sharing

**Comment by brendonw1** [comment]
Yes, I don't know who's asking but if it is in reference to the novelty
sessions on CRCNS repo the channel numbers have been rearranged to reflect
their physical layout (please read through the 'Dataset Description' and
'Channel_Orders' pdf's associated with the dataset - I attached them for
reference). Hope this answers your question.

Best,
Andres

**Comment by brendonw1** [comment]
Sorry, I meant to send this pdf (attached) instead of the 'Recording
Summary'. -AG

**Comment by gmbcrazy** [comment]
Thank you so much!! @brendonw1 

I also e-mailed Peter yesterday, I should use Amplipex instead of Intan mapping.  Together with your information, I start to figure out the probable correct way.

I believe the channel is organized from superficial to deep in the .eeg file as you mentioned.  Attached .jpg shows the LFP traces in one Shank (Animal Buddy, 8x8 probe), ripple power (blue font, RMS calculated from whole session) increase as Channel ID increase.  If I'm correct, that suggest the deep channel is also in center of pyr layer.  Or-else, I wonder if the ripple power could be even stronger when recorded in deep pyr layer instead of center layer?

![rippleexample](https://user-images.githubusercontent.com/32208252/39057195-a4766ed0-4486-11e8-874c-0f0c935d7200.jpg)

BTW, the google sheet you shared should be correct. The one in buzcode-master\preprocessing\probeGeometries\NRXtoAmplipex_Buzsaki64_6x10_untested.xlsx might be wrong. Start from K23.

**Comment by brendonw1** [comment]
This is not my recording or dataset so I think I probably can't help more.
If you want to email me I can help you find the authors who can give more
details.  But yes, if ripple-band power is greater you're closer to pyr
layer.  That said, I'm not sure I see that here in the blue traces... are
the red ones ripple-band filtered and the blue are raw?  In general you
should also see units near the PYR layer and you should see a change in the
sharpwave from slightly upgoing above the pyramidal layer to clearly
downgoing below it.  Here I see the blue trace showing upgoing half-waves
during ripples in the top channels, indicating they are probably above the
PYR layer and by the bottom the ripples are riding on flat to downgoing
half-waves, implying you are at or beneath the PYR layer.  So you may be
right.

**Comment by gmbcrazy** [comment]
@brendonw1 , thank you very much. You've already offer so much help, which helps me a lot.

I might wait for John's feedback before furtherly bother you, yesterday Peter forward my e-mail to him(author).

 Yes blue is raw lfp while red is the filtered. Attached is from another Shank, which is more obviously to see the increased ripple power. It suggests that probably the Channel in .eeg is already arranged from superficial to deep as you said.

![rippleexample2](https://user-images.githubusercontent.com/32208252/39060633-e3df5aba-448f-11e8-9243-5d49f2fc96f8.jpg)

**Comment by gmbcrazy** [comment]
@brendonw1 thank you very much. You've already offer so much help, which helps me a lot.
I might wait for John's feedback before furtherly bother you, yesterday Peter forward my e-mail to him(author).

Yes blue is raw lfp while red is the filtered. ## My bad, previous .jpg is with wrong numbers. Attached is correct one from another Shank, which is obviously to see the increased ripple power until Chan 21, which might be the one mostly closed to Pyr center. Probably the Channel in .eeg is already arranged from superficial to deep as you said.

![rippleexample2](https://user-images.githubusercontent.com/32208252/39061634-fa7db958-4492-11e8-91d2-f83cf01d8cc4.jpg)

**Comment by dlevenstein** [comment]
Hey @gmbcrazy - is this issue solved?

**Comment by gmbcrazy** [comment]
@dlevenstein - yes it is. Thanks a lot.
