### ISSUE TITLE
dev branch, TheStateEditor is broken

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#190]
>> TheStateEditor
20170507_468um_36um_merge.eegstates.mat loaded
Using channel(s): 41  45
Retrieving eeg channel(s)...
Warning: this function assumes int16 precision, if your file is not
int16 use load/resample.m 
> In LoadBinary (line 45)
  In TheStateEditor (line 276) 
Done.
Error using cell/ismember (line 34)
Input A of class cell and input B of class cell must be cell arrays of
character vectors, unless one is a character vector.

Error in INTtoIDX (line 47)
        samestates = ismember(fieldstates,statenames);

Error in TheStateEditor>bz_LoadStates_StateEditorWrapper_In (line 6152)
    SleepState.idx =
    INTtoIDX(SleepState.ints,'statenames',{'WAKE','','NREM','','REM'});

Error in TheStateEditor (line 619)
states = bz_LoadStates_StateEditorWrapper_In(thispath,timevector);

ideas?

**Comment by dlevenstein** [comment]
Found the problem - working on a fix. 

INTtoIDX is looking for fields named "XXXstate".... if a field name is "XXXepisode", for example, the function extractBefore throws an error. I'll have it ignore these.

@brendonw1  - how did you deal with old SleepState files that include MAstate, NREMepisode, etc etc? Did you change MAstate to WAKEstate? Or just leave those files including MAstate?

Note: @DavidTingley, if you want your SleepState files to just have WAKEstate, NREMstate, and REMstate, you should re-run your state scoring. MAstate and all the episodes will be moved to a SleepStateEpisodes.states.mat file

**Comment by brendonw1** [comment]
Hey Dan I don’t think I ever tried loading stateepisodes.states.mat

I’m not in a position to look at this error now tho

**Comment by dlevenstein** [comment]
I'm not loading StateEpisodes.states.mat - david has an old (SleepState.states.mat) file that includes MAstate, NREMepisode, etc etc. I'm just wondering what you did with your old files like this (if anything, maybe this is the first time we've loaded one).

**Comment by brendonw1** [comment]
Yeah it might be the first time. I thought I did but maybe that was two
iterations ago

**Comment by dlevenstein** [comment]
@DavidTingley, how hard would it be for you to re-run SleepScoreMaster, this will fix your problem. (Don't have to re-do EMG or PickSW/THchannel, so it'll be relatively fast.   (I'm going to fix the bug either way, but it would be a good idea for you to update your SleepState.states.mat files)

**Comment by brendonw1** [comment]
If you don’t have time I may have time tomorrow

**Comment by DavidTingley** [comment]
still getting the error, it is due to statenames having an empty

statenames =

  1×5 cell array

    'WAKE'    ''    'NREM'    ''    'REM'



@dlevenstein is there a way to update the file without overwriting the scoring?

**Comment by dlevenstein** [comment]
Uh - that doesn't give me an error, are you sure that's the issue? 
Brendon and I can both run the function with empty strings. Note that I also ran your file after the bug fix and it loaded no problem. Could it be a matlab version issue?..... that would be very frustrating. I'll be uptown tomorrow and we can debug.


No way to update the file without overwriting the scoring, sorry. It should give the same scoring though because it'll use the same channels/LFP metrics. Not worth it to write a whole conversion script for a few files IMO, and you'll be fine with the old ones.

**Comment by DavidTingley** [comment]
It won't be the same if I've already made changes in TheStateEditor ;) 



Thanks for the responses guys!

**Comment by dlevenstein** [comment]
True, though actually I think you can also update (and keep your state editor changes) using the rescore in TheStateEditor with the same thresholds! This might fix your problem too! Try it?

**Comment by DavidTingley** [comment]
fieldstates has strings, statenames has char arrays.  Changing fieldstates back to char arrays seems to avoid ismember.m throwing an error.  How are these variables generated?

**Comment by DavidTingley** [comment]
6bbf7dc fixes things on my end, will close this when you guys confirm it didn't break anything :)

**Comment by dlevenstein** [comment]
no breaks on my end

**Comment by dlevenstein** [comment]
https://www.facebook.com/skillprogramming/videos/2120296211535261/
