### ISSUE TITLE
sessionInfo before spike sorting

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#197]
Some things fail if you make your sessionInfo file before spike sorting. 
Your spike groups become:
spikeGroups.nSamples = [];
spikeGroups.groups = {};
spikeGroups.nGroups = number of anatomical groups 

Which means that when you load bz_getSessionInfo to put in regions, it fails because it tries to load the first element of spikeGroups.groups etc etc.

We clearly don't want to define spike groups before spike sorting, but it would be good to still be able to use anatomical groups... for the purposes of defining channel regions etc. Should the default in bz_getSessionInfo etc to check for spikeGroups and if there are none then use the ElecGp field in the sessionInfo?

Either way, we should change the nGroups field to 0, because number of anatomical groups is not always 0.

This is the issue of group redundancy that is "killing @DavidTingley slowly" - (see line 139 of LoadParameters).

**Comment by brendonw1** [comment]
I agree with this and thought  I did something to address this already.
But regardless glad you're dong it.

**Comment by brendonw1** [comment]
This is resolved now right?

**Comment by dlevenstein** [comment]
yes!
