### ISSUE TITLE
sleepscoremaster plotting turn off

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#211]
Can we add a setting to not plot anything when running sleepscoremaster? The new plots are quite pesky when running on many recordings...

**Comment by DavidTingley** [comment]
perhaps as part of the 'noprompts' argument?

**Comment by dlevenstein** [comment]
Should be very easy to add. There's a line in ssm that calls a function to plot. You can just put that in an if statement with a 'showFig'=false command. Go for it. (Or I can do it when I get back)

**Comment by DavidTingley** [comment]
added to dev
