### ISSUE TITLE
dev branch sleepscoremaster autoscrolling bug

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#212]
typing 'A' to manipulate parameters give the following error now

Undefined function or variable 'detectnameAvailBool'.

Error in TheStateEditor>ViewAutoScoreThresholds (line 4796)

**Comment by brendonw1** [comment]
Did you run without sleepscoremaster first by chance?

**Comment by DavidTingley** [comment]
No, but maybe a previous version? It's an old recording I'm revisiting

**Comment by dlevenstein** [comment]
If you don't have any manual edits you're worried about losing, try re running SSM. 

Is detectnameAvailBool a function or a variable. If it's a function you should check that that's the right function name. (would be internal)

**Comment by brendonw1** [comment]
Hm.  Backwards compatibilty issue?

Your error line is the last line here... after some attempts to set this
detectnameAvailBool thing.

*SleepState = bz_LoadStates(basePath,'SleepState');*

*paramsAvailBool = 0;*
*if isempty(SleepState)*
*    answer = questdlg({'No SleepState.states.mat. Would you like to run
SleepScoreMaster?', 'WARNING: will lose current states!!!'},...*
*        'AutoScore?');*
*    switch answer*
*        case 'Yes'*
*            %answer = questdlg('Use Loaded Channels?','Yes','No, Auto
select channgels for scoring');*
*            SleepScoreMaster(basePath)*
*        case {'No','Cancel'}*
*            return*
*    end*
*elseif isfield(SleepState,'detectorinfo')*
*    if isfield(SleepState.detectorinfo,'detectorname')*
*        detectnameAvailBool = 1;*
*    end*
*    if isfield(SleepState.detectorinfo,'detectionparms')*
*        paramsAvailBool = 1;*
*    end*
*end*

*if detectnameAvailBool*
*    switch SleepState.detectorinfo.detectorname*



*Want to send me your SleepState.states.mat file?  Maybe I'll see if I can
make this backwards compatible*

**Comment by DavidTingley** [comment]
fixed by re-running, but now `ls` throws an error in the matlab terminal after running sleepscoremaster..?

**Comment by DavidTingley** [comment]
Actually it looks like this happens after running TheStateEditor, not sleepscoremaster

**Comment by dlevenstein** [comment]
Bummer. The stateeditor will be harder to debug :p. What's the error?  Is it possible Matlab can create namespace issues for the terminal? That seems unlikely but maybe check if there's a variable ls?

**Comment by DavidTingley** [comment]
I take it back, it just happened after sleepscoremaster....

**Comment by DavidTingley** [comment]
>> ls
Error using ls (line 39)

**Comment by dlevenstein** [comment]
Hm. Try which ls?

**Comment by dlevenstein** [comment]
Are we allowed to see what's on line 39 of ls?

**Comment by DavidTingley** [comment]
error(message('MATLAB:ls:OSError',listing));

**Comment by DavidTingley** [comment]
Figured it out, it is an issue with the SleepStates structure changing.  Originally .detectorname and .detectorparams were fields of the struct, now they have been put as subfields of SleepState.detectorinfo.  I'd rather not re-run all of my sleep scoring to fix this, can we update TheStateEditor to handle both? or write a converter function?

**Comment by DavidTingley** [comment]
`elseif **isfield(SleepState,'detectorinfo')**
    if isfield(SleepState.detectorinfo,'detectorname')
        detectnameAvailBool = 1;
    end
    if isfield(SleepState.detectorinfo,'detectionparms')
        paramsAvailBool = 1;
    end
end`

**Comment by brendonw1** [comment]
Can you send me the old file you have?

**Comment by brendonw1** [comment]
See pull request #229
