### ISSUE TITLE
bz_GetSpikes temporary clu file handling

### ISSUE THREAD

**Issue by rhuszar** [buzsakilab/buzcode#218]
Hi,
I found out that the function can't exclude temporary clu files of this format:

mouse_ID_session_ID.clu.7.09.26.2015.17.19

I fixed the problem on my local machine by adding the following condition to the if statement that looks for clu files that ought to be excluded (line 127):

find(contains(dummy, 'clu')) ~= length(dummy)-1

Best,
Roman

**Comment by brendonw1** [comment]
Do you mean that Line 127 is now:

    if ~isempty(findstr('temp',cluFiles(i).name)) | ~isempty(findstr(
'autosave',cluFiles(i).name)) | isempty(str2num(dummy{length(dummy)}))
| find(contains(dummy,
'clu')) ~= length(dummy)-1


?


Brendon

**Comment by rhuszar** [comment]
Yep!
Roman

**Comment by DavidTingley** [comment]
@rhuszar , could you try submitting this as a pull request to the buzcode/dev branch? I'm happy to show you how tomorrow as well!

**Comment by brendonw1** [comment]
If you guys can take care of this that's great.   If not I can

**Comment by DavidTingley** [comment]
#222 will fix this once merged
