### ISSUE TITLE
Combine bz_LoadPhy and ConverPhyKilo2Neurosuite to ensure spike data saved in neurosuite format 

### ISSUE THREAD

**Issue by raswanson** [buzsakilab/buzcode#263]
Does this make sense? Seems a good stage at which to impose this so we have standardization of our saved files. Do we care? What this would result in is some people having phy + neurosuite formatted files.

**Comment by brendonw1** [comment]
I’m thinking the same function reads both types and outputs a .mat.  I’m
behind that

**Comment by dlevenstein** [comment]
I agree - the standardization of the saved files is in the spikes.cellinfo.mat file. We should allow users to be flexible in their "raw" files, but have a single pipeline that loads in to buzcode.  (i.e. Issue #261)

**Comment by raswanson** [comment]
Agreed. To make explicit the two components of this - 1. Standardization should be at the level of buzcode structs (thus someone might have their spike data in phy format, others in neurosuite, and that's fine), because 2. Our basic I/O spikes fx should be able to generate a spikes.cellinfo.mat file from a range of different common file formats (e.g. neurosuite and phy for now - issue #261 ).

**Comment by brendonw1** [comment]
Exactly

**Comment by dlevenstein** [comment]
Closing - discussion should move to #261
