### ISSUE TITLE
create a bz_GetSpikes function

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#27]
input arguments
-default is all neurons from recording
-by UID
-by shank/channel group
-by region (metadata file required?)

additional optional inputs
- mean waveforms
- max amplitude channel #
- ACG's

Would make sense to start with GetSpikeTimes.m for this

**Comment by DavidTingley** [comment]
@brendonw1 @dlevenstein,  if/when you guys are happy with this function feel free to close this issue (:

**Comment by dlevenstein** [comment]
THIS ISSUE IS CLOSED SO SUCCESSFULLY!
