### ISSUE TITLE
TheStateEditor: overlay not working from SleepState.states.mat file

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#281]
Loading overlay from SleepStates.states.mat file isn't working (using brand new scoring, in dev branch)

**Comment by dlevenstein** [comment]
Looks like the bug is in line 3214
'Undefined function or variable 'obj''

Will look more when I get a chance

**Comment by brendonw1** [comment]
Sub in "FO.fig" for "obj" and it now works.
Also 10 lines later it needs a semicolon
B

**Comment by brendonw1** [comment]
By the way, I didn't know this feature was available and it was on my list
of things to do in the long run!  Thanks

**Comment by brendonw1** [comment]
Would it be OK if we change how this functionality is called upon by the user?  Rather than having it be via the "Choose from file" mode, could we make a separate menu option called "Load Autoscore Metrics" or something?  That way users will know it's possible.

**Comment by dlevenstein** [comment]
That would be awesome!

**Comment by brendonw1** [comment]
I was hoping you’d do it ;)

**Comment by dlevenstein** [comment]
This is addressed in #286 - new pull down option!

**Comment by brendonw1** [comment]
Sweet :)
