### ISSUE TITLE
DetectSPINDLES function missing?

### ISSUE THREAD

**Issue by dalopod** [buzsakilab/buzcode#285]
I cannot find the DetectSPINDLES function that is referenced in detectors/detectStates/SleepScoreMaster/FindSpindlesAndSWs.m anywhere. This may be due to my inexperience, and if so I apologize in advance if it's not actually missing.

**Comment by dlevenstein** [comment]
Ah, sorry - FindSpindlesAndSWs.m and DetectSPINDLES.m were unfinished functions that never should have been imported into buzcode. This was discussed in PR #270 and addressed with PR #274 in the dev branch, but has not yet been pulled into master

**Comment by brendonw1** [comment]
Hi, yeah... we meant to get rid of that FindSpindlesAndSWs.m file... maybe
I forgot?  Not sure how it's still in there.

As for what we tried - it's not fabulous, but I guess it never is (?).... I
think in bz_FindRipples I put something like filter for 10-20Hz, find
durations 400-2000ms something like that. You can try viewing the results
in EventViewer by the way.  We haven't really gone down that rabbit hole
though.

**Comment by dlevenstein** [comment]
it'll be removed in main once we close PR #287
