### ISSUE TITLE
TheStateEditor error when rescoring

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#314]
Ever seen this while re-scoring a recording manually?

Error using  | 
Matrix dimensions must agree.

Error in ClusterStates_DetermineStates (line 95)
shortWRidx =
InIntervals(IDX.timestamps,INT.WAKEstate(shortWints
& (WRints | RWints),:));

Error in TheStateEditor>ReClusterStates_In (line
5569)
[stateintervals,stateidx,~] =
ClusterStates_DetermineStates(...
 
Error while evaluating UIControl Callback.

**Comment by DavidTingley** [comment]
nevermind, I had an old copy of a function in dlevenstein-code that was being called

**Comment by brendonw1** [comment]
Ole DLevenstein code... the good and the bad

**Comment by dlevenstein** [comment]
😬
