### ISSUE TITLE
ignoretime feature for sleepscoremaster

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#315]
Not providing any input for this, throws an error due to empty [] interval set.

Error using InIntervals (line 59)
Incorrect intervals (type 'help InIntervals' for details).
Error in PickSWTHChannel (line 205)
    ignoretimeIDX = InIntervals(t_FFT,ignoretime);
Error in SleepScoreMaster (line 199)
SleepScoreLFP = PickSWTHChannel(basePath,...

**Comment by DavidTingley** [comment]
should be temporarily fixed in acfcf94  though we should consider padding the signal w/ NaNs or zeros rather than removing chunks

**Comment by brendonw1** [comment]
Working on fixing this. This is a problem elsewhere too... did the same if~isempty in a few other places

The nan thing might be a good idea too.

**Comment by dlevenstein** [comment]
The Nan thing would need a complete and unnecessary rewrite of how the algorithm handles ignoreints. Sorry about the empty bug 😬

**Comment by brendonw1** [comment]
Haven’t looked in detail.
Does timing get handled ok if ignore time?

**Comment by brendonw1** [comment]
Like are there still “zero” state assignments for those times?

**Comment by dlevenstein** [comment]
Yup. But that gets handled later. Try it out and double check it works on your end.

**Comment by brendonw1** [comment]
OK good to hear.  Thanks for implementing this.  I may or may not get to
that test - trying to churn through bunch of other stuff

**Comment by dlevenstein** [comment]
Closing issue - this is fixed
