### ISSUE TITLE
Bz_LoadPhy should save spikes in same format as bz_getspikes

### ISSUE THREAD

**Issue by brendonw1** [buzsakilab/buzcode#322]
This way bz_getspikes can be called no matter which spike sorter was used to manually check - this goes along with diea that buzcode code can work on all data the same once it's in buzcode format.

This is a lesser goal than (and therefore separate from) merging bz_loadphy and bz_getspikes (issue#264)

**Comment by brendonw1** [comment]
I think it needs two things
- spikes.numcells field
- spikes.regions field
That's all

**Comment by dlevenstein** [comment]
perhaps there's a way we can have bz_getspikes call bz_loadphy, that way they have to be piped through the same input/output

**Comment by dlevenstein** [comment]
closed in lieu of #261
