### ISSUE TITLE
bz_PhaseModulation - wavelet method - threshold issue

### ISSUE THREAD

**Issue by eliezyer** [buzsakilab/buzcode#324]
Currently the bz_PhaseModulation throws back an error with the wavelet method because it tries to build a power threshold to detect epochs of low amplitude (used in the default hilbert method) - Line 113.

I fixed here but I wanted to confirm before a pull request, does the wavelet method need lfp thresholding or is supposed to be in the whole lfp?

Elie

**Comment by DavidTingley** [comment]
Could you pull request the change so we can take a look? I thought the threshold was used after the LFP power (wavelet or hilbert) was calculated?
