### ISSUE TITLE
CellExplorer Integration

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#346]
CellExplorer should save a cellinfo.mat

**Comment by brendonw1** [comment]
Does it read cell info.mats already?  It should also do that

**Comment by petersenpeter** [comment]
This is already implemented. Brendon, I can give you a short introduction by skype if you want to.

**Comment by dlevenstein** [comment]
Peter - where do we get CellExplorer? Maybe you could put a link to it somewhere in buzcode?
Do you intend that users will be able to contribute to it if we need to change things - add features or fix bugs?

**Comment by brendonw1** [comment]
I found it on Peter's github: https://github.com/petersenpeter/Cell-Explorer

**Comment by petersenpeter** [comment]
Yes it reads spikes.cellinfo.mat files together with event, manipulation. I
started writing up a wiki for it:
https://github.com/petersenpeter/Cell-Explorer/wiki

You are more than welcome to contribute.

I think we should dedicate some time for this at our next meeting.

Den tir. 29. okt. 2019 kl. 13.24 skrev Brendon Watson <
notifications@github.com>:

**Comment by samamckenzie** [comment]
@petersenpeter can you send me your manipulation struct, I can model mine around yours

**Comment by petersenpeter** [comment]
Closing the issue as it has been addressed
https://cellexplorer.org/datastructure/standard-cell-metrics/
