### ISSUE TITLE
Error in Compile Buzcode

### ISSUE THREAD

**Issue by farazmoradi** [buzsakilab/buzcode#410]
Hi, I am running this on MacOs.

Error in compileBuzcode (line 37)
mex -O CCGHeart.c

**Comment by dlevenstein** [comment]
is there any more information about the error? Did any of the other mex lines run? Do you have a c compiler installed?

**Comment by farazmoradi** [comment]
Hi Dan, this is the full error:

> In compileBuzcode (line 28) 
Building with 'Xcode with Clang'.
MEX completed successfully.
Building with 'Xcode with Clang'.
Error using mex
/Users/farazmoradi/Downloads/buzcode-master/analysis/spikes/correlation/CCGHeart.c:1:16: warning: '/*' within block comment
[-Wcomment]
/* CCGEngine.c /*
               ^
/Users/farazmoradi/Downloads/buzcode-master/analysis/spikes/correlation/CCGHeart.c:2:1: warning: '/*' within block comment
[-Wcomment]
/* This is a bare-bones C program whos purpose is to compute
^
/Users/farazmoradi/Downloads/buzcode-master/analysis/spikes/correlation/CCGHeart.c:195:3: error: implicitly declaring library
function 'memcpy' with type 'void *(void *, const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                memcpy(mxGetPr(plhs[1]), (void *)Pairs, PairCnt*sizeof(unsigned int));
                ^
/Users/farazmoradi/Downloads/buzcode-master/analysis/spikes/correlation/CCGHeart.c:195:3: note: include the header <string.h> or
explicitly provide a declaration for 'memcpy'
2 warnings and 1 error generated.


Error in compileBuzcode (line 37)
mex -O CCGHeart.c

**Comment by farazmoradi** [comment]
I think I have installed a C compiler

**Comment by rhuszar** [comment]
what happens if you run "mex CCGHeart.c" ?

**Comment by farazmoradi** [comment]
When i open it in matlab there is no Run option on the top to run the code.

**Comment by dlevenstein** [comment]
Try typing "mex CCGHeart.c" in the command line

**Comment by dlevenstein** [comment]
Worst case scenario, you can comment out compiling CCGHeart? This will just prevent you from using any of the CCG-related functions in the repository.

**Comment by farazmoradi** [comment]
Thanks Dan. I have Commented '' mex -O CCGHeart.c '' in the code and the
problem is solved. But by commenting on this line, will I have any issue
for running the codes and tutorials in the Lab? Is CCGHear.c something
essential?

**Comment by brendonw1** [comment]
CCGHeart allows generation of cross correlations between the spikes of
pairs of neurons (or other phenomena).  Do you anticipate using such
functionality?

**Comment by farazmoradi** [comment]
As I am just starting to work on tutorials I don't think I will need this.
