### ISSUE TITLE
.xml and .lfp

### ISSUE THREAD

**Issue by farazmoradi** [buzsakilab/buzcode#413]
Hi,
I wanted to know how can I produce .XML and .LFP file for my own dataset to run the codes?

**Comment by dlevenstein** [comment]
Hm - if your data was not collected in neuroseries (http://neurosuite.sourceforge.net), I'm not sure there's an easy tool to do this. Anyone else aware of one?

**Comment by brendonw1** [comment]
@farazmoradi You can make .xml files using some tools in here: https://github.com/buzsakilab/buzcode/tree/master/preprocessing/metadata

LFP is a data type for voltage traces - same as .dat specified here
http://neuroscope.sourceforge.net/UserManual/data-files.html

You'd have to generate that from your own data (maybe take out headers, etc)

**Comment by farazmoradi** [comment]
Thank you very much

**Comment by EspeHope** [comment]
I need help converting .dat file from Neuroscope to a file I could read on MATLAB. Any guidance?

**Comment by dlevenstein** [comment]
See Brendon's answer above for creating the .xml. You can use [bz_LFPfromDat](https://github.com/buzsakilab/buzcode/blob/6418ba3b4307c673988bcf6ca44b15927fef5a7d/io/bz_LFPfromDat.m) to make a .lfp file that can then be loaded into Matlab with [bz_GetLFP](https://github.com/buzsakilab/buzcode/blob/6418ba3b4307c673988bcf6ca44b15927fef5a7d/io/bz_GetLFP.m)
