### ISSUE TITLE
Error while using "bz_PowerSpectrumSlope"

### ISSUE THREAD

**Issue by farazmoradi** [buzsakilab/buzcode#414]
Hi, I have received this error while running this function:

My Code: [specslope,spec] = bz_PowerSpectrumSlope(lfp,2,1,'frange',[4 100]);

Error: 

Attempt to execute SCRIPT FindInInterval as a function:
/Volumes/Project/Nastaran
Project/Buzsaki/buzcode-master/externalPackages/FMAToolbox/General/FindInInterval.m

Error in InIntervals (line 129)
	more = FindInInterval(values,[from to],previous);

Error in bz_PowerSpectrumSlope (line 145)
        keeptimes = InIntervals(spec.timestamps,ints);

**Comment by dlevenstein** [comment]
Hm. The error says: "Attempt to execute SCRIPT FindInInterval as a function"
However, FindInInterval should be a compiled c function, not a script.

Did you compileBuzcode?

**Comment by farazmoradi** [comment]
No! I did it right now!

Error using mex
/Volumes/Project/Nastaran
Project/Buzsaki/buzcode-master/analysis/spikes/correlation/CCGHeart.c:1:16: warning:
'/*' within block comment [-Wcomment]
/* CCGEngine.c /*
               ^
/Volumes/Project/Nastaran
Project/Buzsaki/buzcode-master/analysis/spikes/correlation/CCGHeart.c:2:1: warning:
'/*' within block comment [-Wcomment]
/* This is a bare-bones C program whos purpose is to compute
^
/Volumes/Project/Nastaran
Project/Buzsaki/buzcode-master/analysis/spikes/correlation/CCGHeart.c:195:3: error:
implicitly declaring library function 'memcpy' with type 'void *(void *, const void *,
unsigned long)' [-Werror,-Wimplicit-function-declaration]
                memcpy(mxGetPr(plhs[1]), (void *)Pairs, PairCnt*sizeof(unsigned int));
                ^
/Volumes/Project/Nastaran
Project/Buzsaki/buzcode-master/analysis/spikes/correlation/CCGHeart.c:195:3: note:
include the header <string.h> or explicitly provide a declaration for 'memcpy'
2 warnings and 1 error generated.


Error in compileBuzcode (line 37)
mex -O CCGHeart.c

**Comment by dlevenstein** [comment]
This sounds like an issue with your c compiler? check out #410, if you're not going to use the CCG function you can comment out line 37 of compileBuzcode with no problems

**Comment by farazmoradi** [comment]
Solved. Thank you very much!

**Comment by dlevenstein** [comment]
No problemo!
