### ISSUE TITLE
Error in Compile Buzcode

### ISSUE THREAD

**Issue by barryab** [buzsakilab/buzcode#415]
Hi, I am running this on MacOs.

错误使用 cd
无法将目录更改为 /Users/barry/Downloads/buzcode-master/externalPackages/FilterM/externalPackages/xmltree-2.0/@xmltree/private (名称不存在或不是目录)。

出错 compileBuzcode (第 32 行)
cd(['externalPackages' filesep 'xmltree-2.0' filesep '@xmltree' filesep 'private' filesep ''])

**Comment by dlevenstein** [comment]
Hi - there are a number of issues solved in compiling buzcode (search compile buzcode in the issues tab). See if those help? Not sure what your issue is from your message

**Comment by barryab** [comment]
I guess that I might accidentally changed some settings in my Mac, and then I want to try it in Windows, Thanks for your help

**Comment by DavidTingley** [comment]
Closing as this seems solved, feel free to add more info if you continue to have issues!
