### ISSUE TITLE
Restricting bz_FindRipples to specific sleep states

### ISSUE THREAD

**Issue by stephielynn921** [buzsakilab/buzcode#47]
One feature that I rely heavily on in the code I'm using is restricting the ripple detections to NREM sleep from the states.mat file. And as a side note, I don't use the output from the automated sleep scoring (epileptic lfp doesn't do so well with the automated detections) so I'm still using the states.mat file from TheStateEditor.

**Comment by dlevenstein** [comment]
What version of TheStateEditor are you using? I think the up-to-date version on buzcode puts out a baseName.SleepState.states.mat file which is the same whether or not you identified states manually or using the automatic scoring.

If not, it should be updated as all the buzcode functions will use this input type.

**Comment by dlevenstein** [comment]
Does the 'restrict' functionality in bz_FindRipples do this? @DavidTingley

**Comment by DavidTingley** [comment]
Correct, @dlevenstein.  'restrict' is only for the baseline noise calculation, and ripples will still be detected outside of these periods. Is it worth adding/changing the input arguments so there is a 'restrict_baseline_calc' and 'restrict_detection' or something similar?

**Comment by dlevenstein** [comment]
I'm not sure - the user can always use Restrict from FMA after the fact to only look at the events within NREM. 

@stephielynn921 - does this solve your problem? 
NREMrippletimes = Restrict(rippletimes,NREMints) will you to put in a set of NREM interval [start stop] times and then get out only the ripples that happened within those intervals. SleepState.ints.NREM is the intervals you need, which to my knowledge are included in the output of the most recent version of TheStateEditor. If you are using the old form, which is a time vector of state IDs, you can use [this function](https://github.com/dlevenstein/DLevenstein-Code/blob/master/Timeseries%20Utilities/IDXtoINT.m) to convert.

I have a similar function to Restrict that has some additional functionality, which I will sometime soon incorporate into a new and improved bz_Restrict function.

**Comment by brendonw1** [comment]
At worst you can use in_intervals.m from fma
