### ISSUE TITLE
bz_FindRipples to generate an evt file 

### ISSUE THREAD

**Issue by stephielynn921** [buzsakilab/buzcode#48]
If you could include in the FindRipples to create a rip.evt file that can be loaded into Neuroscope to manually check the detection, it would make analysis it a lot smoother for me.

**Comment by raswanson** [comment]
Hey Stephanie,

SaveEvents.m in buzcode will work for you -  it will create a neuroscope .evt file for viewing any event times (a vector)  and descriptions (a cell array of strings) you enter. The documentation is not straightforward, so I attached a quick tutorial re: how you might use it with the ripples.mat structure output by FindRipples. You can then load the .evt file as you would any other .evt file from within neuroscope. Note - neuroscope requires a '3 character' identifier for .evt files, so I added '.RO1' to my file name - add whatever you want.

Good luck!

**Comment by DavidTingley** [comment]
This won't help anytime soon, but one of the future projects we'd like to implement is to allow neuroscope to read *.event.mat structs that bz_findripples and other functions produce.  If you have any other feature ideas for neuroscope, feel free to add them here: https://github.com/buzsakilab/buzcode/projects/3

**Comment by DavidTingley** [comment]
@stephielynn921, did you get @raswanson's solution working?  also, you can use bz_PlotRippleStats.m to display the detected ripple events

**Comment by dlevenstein** [comment]
@stephielynn921 is this issue resolved?

Also, We should make a bz_EventsStatestoEvt (bz_BuzcodeToEvt, bz_BuzcodeToNeuroscope?) function that easily and quickly produces neuroscope files from any buzcode structure, when needed?

**Comment by dlevenstein** [comment]
This issue is stale, I'm going to close it
