### ISSUE TITLE
timestamps/times naming convention

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#73]
move all functions to timestamps naming conventions

**Comment by dlevenstein** [comment]
FYI I updated the wiki for events, and @AntonioFR8 fixed the output of detect_swr.
The wiki now reflects what's needed for EventExplorer, which is the number one tool of buzcode.
Check your detectors when you get a chance

**Comment by DavidTingley** [comment]
bz_findripples will also need to be tweaked, I can tomorrow or this weekend if no one gets to it by then

**Comment by AntonioFR8** [comment]
I can look at that too

**Comment by dlevenstein** [comment]
All data types in wiki have been updated to reflect the "timestamps" naming convention, among some other convention updates.  (i.e. UID instead of cellNum).

Just submitted a pull request which updates bz_FindRipples to reflect the events.mat conventions as outlined in the wiki.

Are there any other detectors that need to be brought up to date? 
If not, once pull request #89 is merged, we can close this issue.
