### ISSUE TITLE
buzcode example structs have problems

### ISSUE THREAD

**Issue by evilrobotxoxo** [buzsakilab/buzcode#87]
The example structs in buzcode have problems, for example, the struct inside the mat files has a name that doesn't match the mat file. Also, there is no example of any actual data, e.g. a spike train. Dan L. asked me to open this issue, but it will be helpful for me also because I want to polish the buzcode<->TStoolbox conversion scripts.

**Comment by DavidTingley** [comment]
-I'll check the behavior, cellinfo, and sessioninfo files when I get a chance.  
-the recordingMetadata should be removed or renamed if it is an animalMetadata type. 
-We should also upload a popinfo example

**Comment by juneshuoyang** [comment]
I am working on cellinfo and sessioninfo now. So I can get back to you on
these two parts within a few days.

**Comment by DavidTingley** [comment]
behavior.mat struct is now correct.  @juneshuoyang, when you're satisfied that cellinfo and sessioninfo example structs are correct, feel free to close this.

**Comment by dlevenstein** [comment]
sessioninfo will take a while and some group discussion, i.e. issue #86.  
I think we'll need to have a group meeting to discuss what will be necessary and iron down how to proceed with this

**Comment by DavidTingley** [comment]
leaving #86 open for discussion, example structs are up to date
