### ISSUE TITLE
LoadParameters and bz_getSessionInfo

### ISSUE THREAD

**Issue by dlevenstein** [buzsakilab/buzcode#93]
LoadParameters has moved far enough away from the original FMA function that is should be renamed bz_LoadParameters and all calls in buzcode should be updated.

bz_getSessionInfo was accidentally deleted, so calls to bz_getSessionInfo were replaced with LoadParameters.

related to issue #86

**Comment by dlevenstein** [comment]
Next step: bz_LoadParameters (or bz_getSessionInfo?) should load from .xml, prompt user for any missing necessary metadata, and then save a baseName.sessionInfo.mat file

**Comment by brendonw1** [comment]
I still think XML should be created from a master metadata entry.  Assuming
XML will quickly become anqituated

**Comment by dlevenstein** [comment]
Eventually, yes, we will need to solve the master metadata problem. This is is an intermediate step to begin converting over old recordings (for which we don't have a master metadata entry) as we use them for analysis, and adding new metadata that isn't in the xml as it becomes required.

**Comment by brendonw1** [comment]
We will start acquring data soon.  What do we need to know/have in terms of
metadata?

**Comment by dlevenstein** [comment]
I'm sorry, we're really not sure at this point.  My thought is that we need something more established before relying on a buzcode format for the sole container of metadata.
If it were me I would continue to use the xml for now, similar to how we still have the clu/res/fet. I think it will take some time for development to settle in to something that works smoothly and works for all. I know you don't agree with that but I don't have a better answer.

**Comment by brendonw1** [comment]
I think I'll use my own system for now - the one I already wrote into
buzcode - since I like it and it's more inclusive and automates things.
It'll also let me refine it and pare it down.

**Comment by dlevenstein** [comment]
I think that makes sense, we'll definitely take your system into account as we work on how we're going to handle development of metadata. 

One thing to consider is that any functions we write will use LoadParameters (soon to be bz_LoadParameters, per issue #93) for compatibility with the maximum number of existing datasets . But if you also keep an accurate xml that mirrors the relevant info in your file then you won't run into any compatibility issues.



At this point, people don't love the idea of using .m files for entry/editing, but a complete better (GUI) solution is not coming any time soon. Also there seems to be conflict between the needs of metadata for storage (everything you want to know about the file, entry during recording) and metadata for analysis (low clutter with ease of accessing the relevant information, conversion of old recordings), which has made it hard to move forward.

**Comment by brendonw1** [comment]
Yeah that makes some sense.  I'll look at load parameters and make sure I'm
consistent with that.   Interestingly I'll be the first person to start a
new dataset from zero with buzcode.  Too bad I'm not physically present to
interact more directly

**Comment by dlevenstein** [comment]
Alas :(    github/slack will have to suffice.

Actually - here's a thought @DavidTingley and I just had:
1) Update buzcode functions to use bz_getSessionInfo, which loads a baseName.sessionInfo.mat file if it exists, and calls LoadParameters if it doesn't. (similar to how bz_GetSpikes deals with baseName.spikes.cellinfo.mat and clu/res/fet files)
2) Check that the loaded sessionInfo structure matches the minimal buzcode requirements ("required" fields in the wiki). We'll make a bz_isSessionInfo file similar to the bz_isEvents/etc files.
3) If any fields as missing, prompt the user to manually enter these values and add them to the structure. (option for 'noprompts' when calling the function)
4) Save the structure as baseName.sessionInfo.mat.  (Perhaps with 'saveMat' defaulting to false, as with bz_GetSpikes)

This way, 
1) we kickstart the process of converting old recordings from the .xml with a combined I/O+convert function (like we did with bz_GetSpikes, which has worked really well), 
2) as we converge on the required fields, the metadata files will be updated to reflect the current requirements, but any additional metadata that a user has stored won't be lost (i.e. your more extensive metadata files from entry during recording day, and any other info from the xml file). 
Do you think that makes sense?

**Comment by brendonw1** [comment]
I'm gonna think about this more carefully over the tomorrow/the weekend
since I have a thing tonight and a talk to prep for for tomorrow am.  But
sounds good to me at first blush

Thank you Dan

**Comment by dlevenstein** [comment]
Good luck!

**Comment by DavidTingley** [comment]
@dlevenstein, how far have we gotten with your 4 steps above? I know you implemented 1)  recently.

**Comment by dlevenstein** [comment]
Haven't yet moved on from that.... will tackle this next week now that am done with all the talks

**Comment by dlevenstein** [comment]
**an update on this issue, addressed with pull request #115** 

[bz_getSessionInfo](https://github.com/buzsakilab/buzcode/blob/692065993a757704de080bb3e74752feba132beb/io/bz_getSessionInfo.m) has the following functionality:
1)
-load baseName.sessionInfo.mat
-if none exists, use [LoadParameters](https://github.com/buzsakilab/buzcode/blob/b320d026d4f21667b1cbda945bbddb6bad85df5f/externalPackages/FMAToolbox/IO/LoadParameters.m.orig) to load the sessionInfo structure from .xml

2)
-check the sessionInfo structure for compliance with buzcode using [bz_isSessionInfo](https://github.com/buzsakilab/buzcode/blob/692065993a757704de080bb3e74752feba132beb/utilities/bz_isSessionInfo.m)
-if no region information has been specified (in a regions field), prompt the user to add regions using [bz_sessionInfoGUI](https://github.com/buzsakilab/buzcode/blob/692065993a757704de080bb3e74752feba132beb/preprocessing/metadata/bz_sessionInfoGUI.m)


Note: bz_sessionInfoGUI can/will be updated to add more fields. And could possibly be further integrated with bz_isSessionInfo, such that bz_isSession info calls bz_sessionInfoGUI prompts the user to add fields whenever it detects them missing?
This more or less addresses 2-4 above.
