### ISSUE TITLE
folder restructuring

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#95]
I'd like to propose some folder restructuring.

1) that we remove the statistics folder (currently empty) and statistical tests can be put in the utilities folder or the relevant analysis subfolder.
2) we rename the plotting folder to visualization, and it can subsume the eventexplorer tool @dlevenstein has been working on.
3) buzcode/preprocessing/fileConversions/ moves to buzcode/utilities/fileConversions/

Thoughts?

**Comment by brendonw1** [comment]
What about moving the probe files out of General Computation also?  Like to
somewhere in preprocessing, or their own folder?

**Comment by DavidTingley** [comment]
yea that's a good idea, they don't really fit under the category of 'computation'.  maybe put them in a 'probeGeometries' folder under preprocessing?

**Comment by brendonw1** [comment]
Yeah sounds good to me

**Comment by dlevenstein** [comment]
IS this issue satisfactorily addressed for now?

**Comment by DavidTingley** [comment]
looks like some of the probeGeometries still aren't in the right spot. I'll fix tonight, this is just my reminder
