### ISSUE TITLE
behavior 2.0

### ISSUE THREAD

**Issue by DavidTingley** [buzsakilab/buzcode#97]
check that all functions reflect the new behavior format

[pos2behav.m](https://github.com/buzsakilab/buzcode/blob/cd800c1625305382e3ff97f273768ffb705c1cc5/preprocessing/fileConversions/pos2behav.m)
[bz_plottrials.m](https://github.com/buzsakilab/buzcode/blob/5d33300001d74570a0b1fb682efe8959e1cf972a/plotting/bz_plotTrials.m)

create a new function to convert original behavior to behavior 2.0 format.

**Comment by dlevenstein** [comment]
bz_plotTrials is OK - nothing was changed in the events substructure.

I updated pos2behav in pull request #98

**Comment by DavidTingley** [comment]
#9 can be rolled into this. 

bz_isBehavior now working.
